config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'

  get 'pages/contact'

  get 'pages/resources'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  get 'categories/index'

  get 'categories/edit'

  get 'categories/new'

  get 'categories/show'

  # get 'home/index' => "home#index"
  root :to => 'home#index'
  resources :posts
  resources :categories
  get 'about', :to => 'pages#about'
  get 'contact', :to => 'pages#contact'
  get 'resources', :to => 'pages#resources'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  # attr_accessor :title, :body, :category_id, :author_id
  # attr_accessor @title, @body, @category_id, @author_id

  # def initialize
  #   @title = @body = @category_id = @author_id=''
  # end

  # def initialize(title='',body='',category_id=0,author_id=0)
  #   @title = title
  #   @body = body
  #   @category_id= category_id
  #   @author_id= author_id
  # end

  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    @title = @category.name
    @posts = @category.posts
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def resources
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new()
    @category=Category.all
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = 'Your post has been saved!'
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
      redirect_to post_path, :notice => 'Your post has been updated'
    else
      render edit
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path :notice => 'Your post has been deleted'
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :category_id, :author_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<ul>
  <% @categories.each do |category| %>
      <li><%= link_to category.name, category %></li>
  <% end %>
</ul>

<br>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @category.name %></h1>
<% if @posts.each do |post| %>
    <h3> <%= link_to post.title, post %> </h3>
    <p><%= post.body %></p>
<% end.empty? %>
    <p>Sorry, there is no posts in this category.</p>
<% end %>
<%= link_to 'Back to Categories', categories_path %>

app/views/home/index.html.erb
<head><title>xiao</title></head>
<body>
<h1>this is HOME page</h1>
<p>i am wrote in Ruby</p>

<% @posts.each do |post| %>
    <p><%= post.title %></p>
    <p><%= post.body %></p>
    <hr>
<% end %>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBlog</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<div>
  <ul class="main-nav" id="'menu">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Blog', posts_path %></li>
    <li><%= link_to 'Contact', contact_path %></li>
    <li><%= link_to 'Resources', resources_path %></li>
  </ul>
</div>

<body>
<% if false %>
    <%= flash.each do |key, value| %>
        <p> <%= value %> </p>
    <% end %>
<% end %>

<%= yield %>
</body>

<style type="text/css">
  #menu {
    font: 12px verdana, arial, sans-serif;
  }

  #menu, #menu li {
    list-style: none;
    padding: 0;
    margin: 0;
  }

  #menu li {
    float: left;
  }

  #menu li a {
    display: block;
    /* 如果是中英文混排的文字，建议用固定宽度
    width:150px;
    height:30px;
    line-height:30px;
    text-align:center;
    */
    padding: 8px 50px;
    background: #3A4953;
    color: #fff;
    text-decoration: none;
    border-right: 1px solid #000;
  }

  #menu li a:hover {
    background: #146C9C;
    color: #fff;
    text-decoration: none;
    border-right: 1px solid #000;
  }

  #menu li a.last {
    border-right: 0; /* 去掉左侧边框 */
  }
</style>

</html>

app/views/pages/about.html.erb
<h1>what's this</h1>
<p>i am learning ror with the help of youtube my-ruby-blog</p>

app/views/pages/contact.html.erb
<h1>Bao</h1>
<p>i am xiao-bao, i am studying ruby on rails. it's cool</p>

app/views/pages/resources.html.erb
<h1>Pages#resources</h1>
<p>Find me in app/views/pages/resources.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for @post do |f| %>
    <p>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.select :category_id, Category.all.collect { |x| [x.name, x.id] }, {:include_blank => 'Select One'} %><br/>
    </p>

    <p>
      <%= f.submit 'Update Post' %>
    </p>

<% end %>
<%= link_to 'Go Back', post_path %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<% @posts.each do |post| %>
    <h3><%=link_to post.title,post %></h3>
    <p><%= post.body %></p>
    <hr>
<% end %>
<%= link_to 'Add New Post',new_post_path %>

app/views/posts/new.html.erb
<h1>Add a New Post</h1>

    <%= form_for @post do |f| %>
        <p>
          <%= f.label :title %>
          <%= f.text_field :title %>
        </p>
        <p>
          <%= f.label :body %>
          <%= f.text_area :body %>
        </p>
        <p>
          <%= f.select :category_id, @category.all.collect { |x| [x.name, x.id] }, {:include_blank => 'Select One'} %>
          <br/>
        </p>
        <p>
          <%= f.submit 'Add Post' %>
        </p>

    <% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<!--<small><%= @post.created_at.strftime('%b %d. %Y') %></small>-->
<small><%= @post.created_at.to_s(:rfc822) %></small>
<p><%= @post.body %></p>
<p>Category: <%= link_to @post.category.name, category_path(:id => @post.category.id) %></p>
<p><%= link_to 'Back', posts_path %></p>

<p>
<% if false %>
<%= link_to 'Edit Post', edit_post_path %> | <%= link_to 'Delete',@post, :confirm => 'Are you sure want to delete?', :method => :delete %>
<% end %>
</p>